
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = '520C97A7C961B235341D5B7425B7E5DA'
    
_lr_action_items = {'RPAREN':([1,10,11,12,13,14,15,16,],[-1,16,-2,-5,-6,-8,-7,-3,]),'POWER':([1,3,10,11,12,13,14,15,16,],[-1,8,8,-2,8,8,8,8,-3,]),'NUMBER':([0,4,5,6,7,8,9,],[1,1,1,1,1,1,1,]),'TIMES':([1,3,10,11,12,13,14,15,16,],[-1,9,9,-2,9,9,-8,-7,-3,]),'PLUS':([1,3,10,11,12,13,14,15,16,],[-1,6,6,-2,-5,-6,-8,-7,-3,]),'LPAREN':([0,4,5,6,7,8,9,],[4,4,4,4,4,4,4,]),'MINUS':([0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,],[5,-1,7,5,5,5,5,5,5,7,-2,-5,-6,-8,-7,-3,]),'$end':([1,2,3,11,12,13,14,15,16,],[-1,0,-4,-2,-5,-6,-8,-7,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'scalar':([0,],[2,]),'num':([0,4,5,6,7,8,9,],[3,10,11,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> scalar","S'",1,None,None,None),
  ('num -> NUMBER','num',1,'p_num_number','integer.py',26),
  ('num -> MINUS num','num',2,'p_num_uminus','integer.py',29),
  ('num -> LPAREN num RPAREN','num',3,'p_num_group','integer.py',32),
  ('scalar -> num','scalar',1,'p_scalar','integer.py',37),
  ('num -> num PLUS num','num',3,'p_num_binop','integer.py',40),
  ('num -> num MINUS num','num',3,'p_num_binop','integer.py',41),
  ('num -> num TIMES num','num',3,'p_num_binop','integer.py',42),
  ('num -> num POWER num','num',3,'p_num_binop','integer.py',43),
]
